
ifeq ($(SDK),1)
BASECPPFLAGS += -D_D3SDK
endif

ifeq ($(DEBUG_MEMORY),1)
BASECPPFLAGS += -DID_DEBUG_MEMORY -DID_REDIRECT_NEWDELETE
endif

ifeq ($(LIBC_MALLOC),1)
BASECPPFLAGS += -DUSE_LIBC_MALLOC=0
endif

ifneq ($(IDNET_HOST),)
CORECPPFLAGS += -DIDNET_HOST=$(IDNET_HOST)
endif

ifeq ($(ID_NOLANADDRESS),1)
CORECPPFLAGS += -DID_NOLANADDRESS
endif

ifeq ($(ID_MCHECK),1)
BASECPPFLAGS += -DID_MCHECK
endif
